@startuml
class Invoice {
+ invoice_head: InvoiceHead
+ invoice_summary: Summary
+ invoice_reference: Optional[InvoiceReference] = None
+ invoice_lines: Optional[Lines] = None
+ product_fee_summary: Optional[List[ProductFeeSummary]] = None
}

class InvoiceHead {
+ supplier_info: SupplierInfo
+ invoice_detail: InvoiceDetail
+ customer_info: Optional[CustomerInfo] = None
+ fiscal_representative_info: Optional[FiscalRepresentative] = None
}

class InvoiceReference {
+ original_invoice_number: str
+ modification_index: int
+ modify_without_master: bool
}

class SupplierInfo {
+ supplier_tax_number: TaxNumber
+ supplier_name: str
+ supplier_address: Address
+ group_member_tax_number: Optional[TaxNumber] = None
+ community_vat_number: Optional[str] = None
+ supplier_bank_account_number: Optional[str] = None
+ individual_exemption: Optional[bool] = None
+ excise_licence_num: Optional[str] = None
}

class CustomerInfo {
+ private_person_indicator: bool
+ customer_vat_data: Optional[CustomerVatData] = None
+ customer_name: Optional[str] = None
+ customer_address: Optional[Address] = None
+ customer_bank_account_number: Optional[str] = None
}

class FiscalRepresentative {
+ fiscal_representative_tax_number: TaxNumber
+ fiscal_representative_name: str
+ fiscal_representative_address: Address
+ fiscal_representative_bank_account_number: Optional[str] = None
}

class InvoiceDetail {
+ invoice_category: InvoiceCategory
+ invoice_delivery_date: date
+ currency_code: str
+ exchange_rate: float
+ invoice_appearance: InvoiceAppearance
+ invoice_delivery_period_start: Optional[date] = None
+ invoice_delivery_period_end: Optional[date] = None
+ invoice_accounting_delivery_date: Optional[date] = None
+ periodical_settlement: Optional[bool] = None
+ small_business_indicator: Optional[bool] = None
+ utility_settlement_indicator: Optional[bool] = None
+ self_billing_indicator: Optional[bool] = None
+ payment_method: Optional[PaymentMethod] = None
+ payment_date: Optional[date] = None
+ cash_accounting_indicator: Optional[bool] = None
+ conventional_invoice_info: Optional[ConventionalInvoiceInfo] = None
+ additional_invoice_data: Optional[List[AdditionalData]] = None
}

class CustomerVatData {
+ customer_tax_number: CustomerTaxNumber
+ community_vat_number: str
+ third_state_tax_id: str
}

class CustomerTaxNumber extends TaxNumber {
+ taxpayer_id: str
+ vat_code: Optional[str]
+ county_code: Optional[str]
+ group_member_tax_number: Optional[TaxNumber]
}

class TaxNumber {
+ taxpayer_id: str
+ vat_code: Optional[str]
+ county_code: Optional[str]
}

class Address {
+ simple_address: SimpleAddress
+ detailed_address: DetailedAddress
}

class SimpleAddress {
+ country_code: str
+ postal_code: str
+ city: str
+ additional_address_detail: str
+ region: Optional[str] = None
}

class DetailedAddress {
+ country_code: str
+ postal_code: str
+ city: str
+ street_name: str
+ public_place_category: str
+ region: Optional[str] = None
+ number: Optional[str] = None
+ building: Optional[str] = None
+ staircase: Optional[str] = None
+ floor: Optional[str] = None
+ door: Optional[str] = None
+ lot_number: Optional[str] = None
}

enum InvoiceCategory {
NORMAL
SIMPLIFIED
AGGREGATE
}

enum InvoiceAppearance {
PAPER
ELECTRONIC
EDI
UNKNOWN
}

enum PaymentMethod {
TRANSFER
CASH
CARD
VOUCHER
OTHER
}

class AdditionalData {
+ data_name: str
+ data_description: str
+ data_value: str
}

class ConventionalInvoiceInfo {
+ order_numbers: Optional[OrderNumbers] = None
+ delivery_notes: Optional[DeliveryNotes] = None
+ shipping_dates: Optional[ShippingDates] = None
+ contract_numbers: Optional[ContractNumbers] = None
+ supplier_company_codes: Optional[SupplierCompanyCodes] = None
+ customer_company_codes: Optional[CustomerCompanyCodes] = None
+ dealer_codes: Optional[DealerCodes] = None
+ cost_centers: Optional[CostCenters] = None
+ project_numbers: Optional[ProjectNumbers] = None
+ general_ledger_account_numbers: Optional[GeneralLedgerAccountNumbers] = None
+ gln_numbers: Optional[GlnNumbers] = None
+ material_numbers: Optional[MaterialNumbers] = None
+ item_numbers: Optional[ItemNumbers] = None
+ ekaer_ids: Optional[EkaerIds] = None
}

class OrderNumbers {
+items: List[str]
}

class DeliveryNotes {
+items: List[str]
}

class ShippingDates {
+items: List[str]
}

class ContractNumbers {
+items: List[str]
}

class SupplierCompanyCodes {
+items: List[str]
}

class CustomerCompanyCodes {
+items: List[str]
}

class DealerCodes {
+items: List[str]
}

class CostCenters {
+items: List[str]
}

class ProjectNumbers {
+items: List[str]
}

class GeneralLedgerAccountNumbers {
+items: List[str]
}

class GlnNumbers {
+items: List[str]
}

class MaterialNumbers {
+items: List[str]
}

class ItemNumbers {
+items: List[str]
}

class EkaerIds {
+items: List[str]
}

class Lines {
+ merged_item_indicator: bool
+ items: List[Line]
}

class Line {
+ line_number: int
+ line_expression_indicator: bool
+ line_modification_reference: Optional[LineModificationReference] = None
+ references_to_other_lines: Optional[ReferencesToOtherLines] = None
+ advance_data: Optional[AdvanceData] = None
+ product_codes: Optional[ProductCodes] = None
+ line_nature_indicator: Optional[LineNatureIndicator] = None
+ line_description: Optional[str] = None
+ quantity: Optional[float] = None
+ unit_of_measure: Optional[UnitOfMeasure] = None
+ unit_of_measure_own: Optional[str] = None
+ unit_price: Optional[float] = None
+ unit_price_huf: Optional[float] = None
+ line_discount_data: Optional[DiscountData] = None
+ line_amounts: Union[Optional[LineAmountsNormal], Optional[LineAmountsSimplified]] = None
+ intermediated_service: Optional[bool] = None
+ aggregate_invoice_line_data: Optional[AggregateInvoiceLineData] = None
+ new_transport_mean: Optional[NewTransportMean] = None
+ deposit_indicator: Optional[bool] = None
+ margin_scheme_indicator: Optional[MarginScheme] = None
+ obligated_for_product_fee: Optional[bool] = None
+ gpc_excise: Optional[float] = None
+ diesel_oil_purchase: Optional[DieselOilPurchase] = None
+ neta_declaration: Optional[bool] = None
+ product_fee_clause: Optional[ProductFeeClause] = None
+ line_product_fee_content: Optional[List[ProductFeeData]] = None
+ conventional_line_info: Optional[ConventionalInvoiceInfo] = None
+ additional_line_data: Optional[List[AdditionalData]] = None
}

class LineModificationReference {
+ line_number_reference: int
+ line_operation: LineOperation
}

enum LineOperation{
+ CREATE
+ MODIFY
}

class ReferencesToOtherLines {
+ items: List[int] = None
}

class AdvanceData {
+ advance_indicator: bool
+ advance_payment_data: AdvancePaymentData
}

class AdvancePaymentData {
+ advance_original_invoice: str
+ advance_payment_date: date
+ advance_exchange_rate: float
}

class ProductCodes {
+ items: List[ProductCode]
}

class ProductCode {
+ product_code_category: ProductCodeCategory,
+ product_code_value: Union[ProductCodeValue, ProductCodeOwnValue]
}

class ProductCodeValue extends str

class ProductCodeOwnValue extends str

enum ProductCodeCategory {
+ VTSZ
+ SZJ
+ KN
+ AHK
+ CSK
+ KT
+ EJ
+ TESZOR
+ OWN
+ OTHER
}

enum LineNatureIndicator {
+ PRODUCT
+ SERVICE
+ OTHER
}

enum UnitOfMeasure {
+ PIECE
+ KILOGRAM
+ TON
+ KWH
+ DAY
+ HOUR
+ MINUTE
+ MONTH
+ LITER
+ KILOMETER
+ CUBIC_METER
+ METER
+ LINEAR_METER
+ CARTON
+ PACK
+ OWN
}

class DiscountData {
+ discount_description: Optional[str] = None
+ discount_value: Optional[float] = None
+ discount_rate: Optional[float] = None
}

class LineAmountsNormal {
+ line_net_amount_data: LineNetAmountData
+ line_vat_rate: VatRate
+ line_vat_data: Optional[LineVatData] = None
+ line_gross_amount_data: Optional[LineGrossAmountData] = None
}

class LineNetAmountData {
+ line_net_amount: float
+ line_net_amount_huf: float
}

class VatRate {
+ value: Union[
        VatPercentage,
        VatExemption,
        VatOutOfScope,
        VatDomesticReverseCharge,
        MarginSchemeVat,
        MarginSchemeNoVat
    ]
}

class VatPercentage extends str

class VatExemption extends str

class VatOutOfScope {
+ value: bool
}

class VatDomesticReverseCharge {
+ value: bool
}

class MarginSchemeVat {
+ value: bool
}

class MarginSchemeNoVat {
+ value: bool
}


Invoice "1" -- "0..1" InvoiceReference
Invoice "1" -- "1" InvoiceHead
Invoice "1" -- "1" Lines
InvoiceHead "1" -- "1" SupplierInfo
InvoiceHead "1" -- "0..1" CustomerInfo
InvoiceHead "1" -- "0..1" FiscalRepresentative
InvoiceHead "1" -- "1" InvoiceDetail
CustomerInfo "1" ---- "0..1" CustomerVatData
CustomerVatData "1" -- "1" CustomerTaxNumber
CustomerTaxNumber "1" --- "0..1" TaxNumber
SupplierInfo "1" --- "1" TaxNumber
SupplierInfo "1" --- "0..1" TaxNumber
SupplierInfo "1" -- "1" Address
CustomerInfo "1" -- "0..1" Address
FiscalRepresentative "1" -- "1" Address
Address "1" -- "0..1" SimpleAddress
Address "1" -- "0..1" DetailedAddress
InvoiceDetail -- InvoiceCategory
InvoiceDetail -- InvoiceAppearance
InvoiceDetail -- PaymentMethod
InvoiceDetail "1" -- "0..*" AdditionalData
InvoiceDetail "1" -- "0..1" ConventionalInvoiceInfo
ConventionalInvoiceInfo "1" -- "0..1" OrderNumbers
ConventionalInvoiceInfo "1" --- "0..1" DeliveryNotes
ConventionalInvoiceInfo "1" -- "0..1" ShippingDates
ConventionalInvoiceInfo "1" --- "0..1" ContractNumbers
ConventionalInvoiceInfo "1" -- "0..1" SupplierCompanyCodes
ConventionalInvoiceInfo "1" --- "0..1" CustomerCompanyCodes
ConventionalInvoiceInfo "1" -- "0..1" DealerCodes
ConventionalInvoiceInfo "1" --- "0..1" CostCenters
ConventionalInvoiceInfo "1" -- "0..1" ProjectNumbers
ConventionalInvoiceInfo "1" --- "0..1" GeneralLedgerAccountNumbers
ConventionalInvoiceInfo "1" -- "0..1" GlnNumbers
ConventionalInvoiceInfo "1" --- "0..1" MaterialNumbers
ConventionalInvoiceInfo "1" -- "0..1" ItemNumbers
ConventionalInvoiceInfo "1" --- "0..1" EkaerIds
Lines "1" --- "0..*" Line
Line "1" --- "0..1" LineModificationReference
LineModificationReference "1" --- "1" LineOperation
Line "1" --- "0..1" ReferencesToOtherLines
Line "1" --- "0..1" AdvanceData
AdvanceData "1" --- "1" AdvancePaymentData
Line "1" -- "0..1" ProductCodes
ProductCodes "1" -- "0..*" ProductCode
ProductCode "1" -- "1" ProductCodeCategory
ProductCode "1" -- "1" ProductCodeValue
ProductCode "1" -- "1" ProductCodeOwnValue
Line "0" -- "1" LineNatureIndicator
Line "0" -- "1" UnitOfMeasure
Line "0" -- "1" DiscountData
Line "0" -- "1" LineAmountsNormal
LineAmountsNormal "1" -- "1" LineNetAmountData
LineAmountsNormal "1" -- "1" VatRate
VatRate "0" -- "1" VatPercentage
VatRate "0" -- "1" VatExemption
VatRate "0" -- "1" VatOutOfScope
VatRate "0" -- "1" VatDomesticReverseCharge
VatRate "0" -- "1" MarginSchemeVat
VatRate "0" -- "1" MarginSchemeNoVat
@enduml