@startuml
class Invoice {
+ invoice_head: InvoiceHead
+ invoice_summary: Summary
+ invoice_reference: Optional[InvoiceReference] = None
+ invoice_lines: Optional[Lines] = None
+ product_fee_summary: Optional[List[ProductFeeSummary]] = None
}

class InvoiceHead {
+ supplier_info: SupplierInfo
+ invoice_detail: InvoiceDetail
+ customer_info: Optional[CustomerInfo] = None
+ fiscal_representative_info: Optional[FiscalRepresentative] = None
}

class InvoiceReference {
+ original_invoice_number: str
+ modification_index: int
+ modify_without_master: bool
}

class SupplierInfo {
+ supplier_tax_number: TaxNumber
+ supplier_name: str
+ supplier_address: Address
+ group_member_tax_number: Optional[TaxNumber] = None
+ community_vat_number: Optional[str] = None
+ supplier_bank_account_number: Optional[str] = None
+ individual_exemption: Optional[bool] = None
+ excise_licence_num: Optional[str] = None
}

class CustomerInfo {
+ private_person_indicator: bool
+ customer_vat_data: Optional[CustomerVatData] = None
+ customer_name: Optional[str] = None
+ customer_address: Optional[Address] = None
+ customer_bank_account_number: Optional[str] = None
}

class FiscalRepresentative {
+ fiscal_representative_tax_number: TaxNumber
+ fiscal_representative_name: str
+ fiscal_representative_address: Address
+ fiscal_representative_bank_account_number: Optional[str] = None
}

class InvoiceDetail {
+ invoice_category: InvoiceCategory
+ invoice_delivery_date: date
+ currency_code: str
+ exchange_rate: float
+ invoice_appearance: InvoiceAppearance
+ invoice_delivery_period_start: Optional[date] = None
+ invoice_delivery_period_end: Optional[date] = None
+ invoice_accounting_delivery_date: Optional[date] = None
+ periodical_settlement: Optional[bool] = None
+ small_business_indicator: Optional[bool] = None
+ utility_settlement_indicator: Optional[bool] = None
+ self_billing_indicator: Optional[bool] = None
+ payment_method: Optional[PaymentMethod] = None
+ payment_date: Optional[date] = None
+ cash_accounting_indicator: Optional[bool] = None
+ conventional_invoice_info: Optional[ConventionalInvoiceInfo] = None
+ additional_invoice_data: Optional[List[AdditionalData]] = None
}

class CustomerVatData {
+ customer_tax_number: CustomerTaxNumber
+ community_vat_number: str
+ third_state_tax_id: str
}

class CustomerTaxNumber extends TaxNumber {
+ taxpayer_id: str
+ vat_code: Optional[str]
+ county_code: Optional[str]
+ group_member_tax_number: Optional[TaxNumber]
}

class TaxNumber {
+ taxpayer_id: str
+ vat_code: Optional[str]
+ county_code: Optional[str]
}

class Address {
+ simple_address: SimpleAddress
+ detailed_address: DetailedAddress
}

class SimpleAddress {
+ country_code: str
+ postal_code: str
+ city: str
+ additional_address_detail: str
+ region: Optional[str] = None
}

class DetailedAddress {
+ country_code: str
+ postal_code: str
+ city: str
+ street_name: str
+ public_place_category: str
+ region: Optional[str] = None
+ number: Optional[str] = None
+ building: Optional[str] = None
+ staircase: Optional[str] = None
+ floor: Optional[str] = None
+ door: Optional[str] = None
+ lot_number: Optional[str] = None
}

enum InvoiceCategory {
NORMAL
SIMPLIFIED
AGGREGATE
}

enum InvoiceAppearance {
PAPER
ELECTRONIC
EDI
UNKNOWN
}

enum PaymentMethod {
TRANSFER
CASH
CARD
VOUCHER
OTHER
}

class AdditionalData {
+ data_name: str
+ data_description: str
+ data_value: str
}

class ConventionalInvoiceInfo {
+ order_numbers: Optional[OrderNumbers] = None
+ delivery_notes: Optional[DeliveryNotes] = None
+ shipping_dates: Optional[ShippingDates] = None
+ contract_numbers: Optional[ContractNumbers] = None
+ supplier_company_codes: Optional[SupplierCompanyCodes] = None
+ customer_company_codes: Optional[CustomerCompanyCodes] = None
+ dealer_codes: Optional[DealerCodes] = None
+ cost_centers: Optional[CostCenters] = None
+ project_numbers: Optional[ProjectNumbers] = None
+ general_ledger_account_numbers: Optional[GeneralLedgerAccountNumbers] = None
+ gln_numbers: Optional[GlnNumbers] = None
+ material_numbers: Optional[MaterialNumbers] = None
+ item_numbers: Optional[ItemNumbers] = None
+ ekaer_ids: Optional[EkaerIds] = None
}

class OrderNumbers {
+items: List[str]
}

class DeliveryNotes {
+items: List[str]
}

class ShippingDates {
+items: List[str]
}

class ContractNumbers {
+items: List[str]
}

class SupplierCompanyCodes {
+items: List[str]
}

class CustomerCompanyCodes {
+items: List[str]
}

class DealerCodes {
+items: List[str]
}

class CostCenters {
+items: List[str]
}

class ProjectNumbers {
+items: List[str]
}

class GeneralLedgerAccountNumbers {
+items: List[str]
}

class GlnNumbers {
+items: List[str]
}

class MaterialNumbers {
+items: List[str]
}

class ItemNumbers {
+items: List[str]
}

class EkaerIds {
+items: List[str]
}

Invoice "1" --* "0..1" InvoiceReference
Invoice "1" --* "1" InvoiceHead
InvoiceHead "1" --* "1" SupplierInfo
InvoiceHead "1" --* "0..1" CustomerInfo
InvoiceHead "1" --* "0..1" FiscalRepresentative
InvoiceHead "1" --* "1" InvoiceDetail
CustomerInfo "1" ----* "0..1" CustomerVatData
CustomerVatData "1" --* "1" CustomerTaxNumber
CustomerTaxNumber "1" ---* "0..1" TaxNumber
SupplierInfo "1" ---* "1" TaxNumber
SupplierInfo "1" ---* "0..1" TaxNumber
SupplierInfo "1" --* "1" Address
CustomerInfo "1" --* "0..1" Address
FiscalRepresentative "1" --* "1" Address
Address "1" --* "0..1" SimpleAddress
Address "1" --* "0..1" DetailedAddress
InvoiceDetail -- InvoiceCategory
InvoiceDetail -- InvoiceAppearance
InvoiceDetail -- PaymentMethod
InvoiceDetail "1" -- "0..*" AdditionalData
InvoiceDetail "1" -- "0..1" ConventionalInvoiceInfo
ConventionalInvoiceInfo "1" -- "0..1" OrderNumbers
ConventionalInvoiceInfo "1" -- "0..1" DeliveryNotes
ConventionalInvoiceInfo "1" -- "0..1" ShippingDates
ConventionalInvoiceInfo "1" -- "0..1" ContractNumbers
ConventionalInvoiceInfo "1" -- "0..1" SupplierCompanyCodes
ConventionalInvoiceInfo "1" -- "0..1" CustomerCompanyCodes
ConventionalInvoiceInfo "1" -- "0..1" DealerCodes
ConventionalInvoiceInfo "1" -- "0..1" CostCenters
ConventionalInvoiceInfo "1" -- "0..1" ProjectNumbers
ConventionalInvoiceInfo "1" -- "0..1" GeneralLedgerAccountNumbers
ConventionalInvoiceInfo "1" -- "0..1" GlnNumbers
ConventionalInvoiceInfo "1" -- "0..1" MaterialNumbers
ConventionalInvoiceInfo "1" -- "0..1" ItemNumbers
ConventionalInvoiceInfo "1" -- "0..1" EkaerIds
@enduml